---
- name: Ensure k0s service unit is applied
  ansible.builtin.template:
    src: "k0s-{{ k0s_role }}.service.j2"
    dest: "/etc/systemd/system/k0s-{{ k0s_role }}.service"
    owner: root
    group: root
    mode: '0644'

- name: Ensure k0s service is enabled and started
  ansible.builtin.systemd:
    name: "k0s-{{ k0s_role }}.service"
    state: started
    enabled: true
    daemon_reload: true