---
# -----------------------------------------------------------------------------
# GENERAL
# -----------------------------------------------------------------------------
k0s_role: worker

# -----------------------------------------------------------------------------
# CONFIGURATIONS
# -----------------------------------------------------------------------------
k0s_worker_config_containerd_template: fileserver/containerd.toml.j2
k0s_worker_profile: default